### ISSUE TITLE
Using with DataFramesMeta.@transform macro

### ISSUE THREAD

**Issue by metanoid** [jkrumbiegel/Chain.jl#3]
I found the following example does not work:

```julia
using DataFrames, DataFramesMeta
using Chain

df = DataFrame(A = 1:3, B = [2, 1,2])
@chain df begin @transform(a = 2 * :A, b = :A .+ :B) end # does not work
@transform(df, a = 2 * :A, b = :A .+ :B) # does work
@chain df begin @transform(_, a = 2 * :A, b = :A .+ :B) end # works, but I don't understand why
```

Are there any demos of how to use Chain.jl with DataFramesMeta.jl?

**Comment by jkrumbiegel** [comment]
Hm good point, that has to do with the fact that I splice arguments into call expressions automatically, but not into macrocall expressions. I could do macrocalls as well, but because macros do all kinds of weird things I thought it's harder to reason about all the different behaviors that this would enable.

I guess it's not so bad to do macrocalls as well, as this behavior only happens without underscores anyway, so in case there is something really weird going on with argument splicing, one can always fall back to using the underscore.

**Comment by jkrumbiegel** [comment]
Ok, I've just put v0.4 up for registration. I tried your example and it works for me now. I just added the same splicing for macrocalls as for normal calls and updated the readme to reflect that

**Comment by metanoid** [comment]
Tested and working, thanks!
