### ISSUE TITLE
Single call inline chain fails

### ISSUE THREAD

**Issue by jariji** [jkrumbiegel/Chain.jl#51]
```jl
julia> @chain abs(1) 
ERROR: LoadError: Can't insert a first argument into:
1.
```

I'm interactively building a chain one step at a time, so I want to initially evaluate the first step. The block version works

```jl
@chain abs(1) begin
    
end # 1
```

just not the inline version.

**Comment by jariji** [comment]
Bump

**Comment by jkrumbiegel** [comment]
I've been thinking a bit about this. There are currently three different modes supported:

Inline:
```julia
@chain a b c
```

Block with prefix argument (original syntax):
```julia
@chain a begin
    b
    c
end
```

Block without prefix:

```julia
@chain begin
    a
    b
    c
end
```

So my thought is that the original syntax is kind of a combination of the other two, and it seems to me in principle there's just one mode, but it's currently not implemented that way. That one mode would be inline like `@chain a b c` but if there's a `begin end` block as one of the arguments, it is flattened. The difference between that and what we currently have is that if we apply that consistently, we kind of change the behavior for things like `@chain a b begin something end` because nothing keeps one of the later inline arguments from being a `begin end` block. On the other hand, I feel like that is rather a design gap that I would want to close, and would probably merit going to a next minor version.

In that new mode you could then do stuff like this as well if you wanted to:

```julia
@chain a b begin
    c
    d
end e f
```

**Comment by jariji** [comment]
Fwiw I don't really like the "block without prefix" form, it seems like a weird special case. Compatibility aside, wouldn't it be simpler to just say the options are

```jl
@chain data block
@chain data expr...
```

**Comment by jkrumbiegel** [comment]
It may be simpler in some ways, but the single block style was introduced because some users had long first variable names that looked cluttered inline with the `@chain begin`. And so yeah, for compatibility it has to stay that way. And then I find having three different syntax styles more complicated than having one that the others derive from. For 99% of users it will make no difference either way.
