### ISSUE TITLE
Performance comparison with function composition

### ISSUE THREAD

**Issue by Oblynx** [jkrumbiegel/Chain.jl#7]
`@chain` rewrites each expression to assign to temporary variables:
https://github.com/jkrumbiegel/Chain.jl/blob/747639ebd62ae6318b30f563d057b2a6f66d10c9/src/Chain.jl#L46

Can this lead to a performance tradeoff compared with plain-Julia function composition?
Especially in the case of broadcasting, I suppose this should break [syntactic loop fusion](https://julialang.org/blog/2017/01/moredots/), or not?

**Comment by jkrumbiegel** [comment]
I think it can, yes, but the things I made it for (Dataframe manipulation mostly) don't work with fused expressions anyway. That's because you can't express a groupby combine strategy as a kernel function iterating once over your original dataframe.

So yes, don't use this as a replacement for broadcasting syntax. To me it's also important that error messages are informative, which works better with the stepwise approach, so it's just a tradeoff

**Comment by Oblynx** [comment]
I totally agree and thanks a lot for your package 😊 

I've been using lazy.jl @> so far, but I'm gonna give this a try because of the debugging syntax. I just wanted to clear out the inherent limitation.
